title: Denys Kryvytskyi | Software Engineer
author:
  name: 2022 Denys Kryvytskyi
  email: kryvytskyi.denys@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Hi! I'm Denys Kryvytskyi. Here you can find information about my projects.
  Also I post articles about game development and software engineering.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  # skin: solarized

  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    github:  kryvytskyidenys
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: kryvytskyidenys
    # pinterest: jekyll
    # youtube: jekyll
    youtube_channel: UCx90zcUS9qnt0JInGaot2IQ
    youtube_channel_name: Denys Kryvytskyi
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

paginate: 5

plugins:
 - jekyll-feed
 - jekyll-paginate
 - jekyll-seo-tag
